services:
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
    controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver
    request_stack:
        class: Symfony\Component\HttpFoundation\RequestStack
    http_kernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments: [ @event_dispatcher, @controller_resolver, @request_stack ]
